//! # Heap Sparse Set
//! 4/22/2026 - Nyx
//! 
//! Sparse set implementation used to emulate the heap of the interpreter.
//! The ids generated by the sparse set function the same a pointers.
//! 
//! This is a standard three set sparse set storing a sparse, dense, and unused sets. 
//! The Sparse set is indexed as ids each cell in the array points to its corresponding 
//! location in the dense set. The Dense set holds the actual data compacted into a small iterable variant.
//! The Unused set stores all the previously deleted ids int the sparse set allowing for them to be reused 
//! later.
//! 
//! The purpose of a Sparse Set is to efficiently store id'd data in a compacted way that can still be accessed 
//! after a piece of data was deleted. Sparse Sets do this by combining two arrays to represent a sparse hole full
//! array and a dense compacted array of data.

// INCLUDES -----
const std = @import("std");
const objects = @import("objects.zig");
// ----- INCLUDES


/// Heap Sparse Set
/// 
/// Sparse set implementation used to emulate the heap of the 
/// interpreter's memory.
pub const HeapSparseSet = struct {

    /// The Default capacity of all three sets
    const DEFAULT_SET_CAPACITY: usize = 16;
    
    /// General purpose allocator
    gpa: std.mem.Allocator,

    /// The Sparse 'hole-y' set
    sparse: Set(usize),

    /// The dense compacted set of data
    dense: Set(objects.Object),

    /// Set of all previously used and deleted ids.
    unused: Set(objects.IdentifierHash),

    /// Single Set 
    /// 
    /// Stores the data, the current size, and the current capacity.
    fn Set(comptime T: type) type {
        return struct {
            const Self = @This();

            /// The sets data
            set: []T,

            /// The current size of the set
            size: usize = 0,

            /// The current capacity of the set
            capacity: usize = DEFAULT_SET_CAPACITY,

            fn init(memory: []T) Self {
                return .{
                    .set = memory
                };
            }

            fn deinit(self: *Self, gpa: std.mem.Allocator) void {
                gpa.free(self.set);
            }
        };
    }

    pub fn init(gpa: std.mem.Allocator) !HeapSparseSet {
        const sparse_set = try gpa.alloc(usize, DEFAULT_SET_CAPACITY);
        @memset(sparse_set, std.math.maxInt(usize));

        return .{
            .gpa = gpa,
            .sparse = .init(sparse_set),
            .dense = .init(try gpa.alloc(objects.Object, DEFAULT_SET_CAPACITY)),
            .unused = .init(try gpa.alloc(usize, DEFAULT_SET_CAPACITY)),
        };
    }

    pub fn deinit(self: *HeapSparseSet) void {
        self.sparse.deinit(self.gpa);
        self.dense.deinit(self.gpa);
        self.unused.deinit(self.gpa);
    }

    /// Pushes an id onto the unused set to be reused later.
    /// 
    /// Automatically grows the unused set when the size reaches the capacity.
    fn push_unused(self: *HeapSparseSet, id: objects.IdentifierHash) !void {
        if (self.unused.size >= self.unused.capacity) {
            self.*.unused.capacity *= 2;
            self.*.unused.set = try self.gpa.realloc(self.unused.set, self.unused.capacity);
        }

        self.*.unused.set[self.unused.size] = id;
        self.*.unused.size += 1;
    }

    /// Pops an id from the top of the unused set. If the unused set is empty it will return null.
    fn pop_unused(self: *HeapSparseSet) ?objects.IdentifierHash {
        if (self.unused.size == 0)
            return null;

        self.*.unused.size -= 1;
        return self.unused.set[self.unused.size];
    }

    /// Emplaces a piece of data into the dense set returning its designated id.
    /// 
    /// # Example
    /// 
    /// ```zig
    /// const std = @import("std");
    /// const HeapSparseSet = @include("heap-sparse-set.zig");
    /// 
    /// var set: HeapSparseSet = try .init(std.heap.page_allocator);
    /// const id = set.emplace(.{ .int = 60 });
    /// 
    /// _ = id;
    /// ```
    pub fn emplace(self: *HeapSparseSet, data: objects.Object) !objects.IdentifierHash {
        const id: objects.IdentifierHash = if (self.pop_unused()) |unused_id|
            unused_id 
        else create_id: {
            if (self.sparse.size >= self.sparse.capacity) {
                self.*.sparse.capacity *= 2;
                self.*.sparse.set = try self.gpa.realloc(self.sparse.set, self.sparse.capacity);
            }

            defer self.*.sparse.size += 1;
            break :create_id self.sparse.size;
        };

        const idx = self.dense.size;
        self.*.sparse.set[id] = idx;
        self.*.dense.set[idx] = data;
        self.*.dense.size += 1;

        return id;        
    }

    /// Deletes and frees the data designated by an id.
    /// 
    /// # Example
    /// 
    /// ```zig
    /// const std = @import("std");
    /// const HeapSparseSet = @include("heap-sparse-set.zig");
    /// 
    /// var set: HeapSparseSet = try .init(std.heap.page_allocator);
    /// const id = try set.emplace(.{ .int = 60 });
    /// 
    /// try set.free(id);
    /// ```
    pub fn free(self: *HeapSparseSet, id: objects.IdentifierHash) !void {
        const removing_idx = self.sparse.set[id];

        const swapping_idx = self.dense.size - 1;
        const swapping_id = find_swapping_id: {
            var i: usize = 0;
            while (i < self.sparse.size and self.sparse.set[id] != swapping_idx)
                i += 1;
            break :find_swapping_id i;
        };

        self.*.dense.set[removing_idx] = self.dense.set[swapping_idx];
        self.*.sparse.set[swapping_id] = removing_idx;
        self.*.sparse.set[id] = std.math.maxInt(usize);

        self.*.dense.size -= 1;
        try self.push_unused(id);
    }

    /// Gets a pointer to a piece of data from its id.
    /// 
    /// # Example
    /// 
    /// Out Of Date!
    /// ```zig
    /// const std = @import("std");
    /// const HeapSparseSet = @include("heap-sparse-set.zig");
    /// const objects = @include("objects.zig");
    /// 
    /// var set: HeapSparseSet = try .init(std.heap.page_allocator);
    /// const id = try set.emplace(.{ .int = 60 });
    /// defer try set.free(id);
    /// 
    /// const val: *const objects.Object = set.get(id);
    /// ```
    pub fn get(self: *const HeapSparseSet, id: objects.IdentifierHash) objects.Object.ObjectRef {
        return self.dense.set[self.sparse.set[id]].ref();
    }

};